################################################################################
MLI_FILE		= cordova_push.mli
## Name which will be used in -package with ocamlfind
LIB_NAME		= cordova-plugin-push-notifications
################################################################################
